from pathlib import Path
r=Path("/tmp/overlay")
def rw(p,f):
 p=r/p;s=p.read_text(encoding="utf-8");p.write_text(f(s),encoding="utf-8")
def html(s):
 s=s.replace('<section class="overall-card">','<div class="brand-divider" aria-hidden="true"></div><div class="nav-details" id="navDetails"><section class="overall-card">',1)
 s=s.replace('<div class="filters" id="filters">','</div><div class="filters" id="filters">',1)
 return s.replace('</div>\n    </header>\n\n    <main id="treeScroll"','</div><button class="nav-collapse-btn" id="navCollapseBtn" type="button" aria-expanded="true" aria-label="네비게이션 접기"><span></span></button>\n    </header>\n\n    <main id="treeScroll"',1)
rw(Path("shared-web/index.html"),html)
def js(s):
 s=s.replace("lastTreeScroll:0,headerHidden:false,scrollVelocity:0,scrollFrame:0,","lastTreeScroll:0,navCollapsed:false,scrollVelocity:0,scrollFrame:0,contextParentId:null,")
 s=s.replace("$('#expandAllBtn').onclick=()=>{this.sfx('CLICK');this.toggleAll()};","$('#expandAllBtn').onclick=e=>{this.sfx('CLICK');this.toggleAll();e.currentTarget.blur()};$('#navCollapseBtn').onclick=()=>{this.sfx('CLICK');this.setNavCollapsed(!this.navCollapsed)};")
 s=s.replace("const sc=$('#treeScroll');sc.addEventListener('scroll',()=>this.handleHeaderScroll(),{passive:true});sc.addEventListener('wheel',e=>this.smoothWheel(e),{passive:false});","const sc=$('#treeScroll');sc.addEventListener('wheel',e=>this.smoothWheel(e),{passive:false});this.navCollapsed=localStorage.getItem('mira-checklist-nav-collapsed')==='1';this.setNavCollapsed(this.navCollapsed,false);")
 s=s.replace("$$('.close-dialog').forEach(b=>b.onclick=()=>this.closeDialogs(true));","$$('.close-dialog').forEach(b=>b.onclick=()=>this.requestCloseCurrent());")
 s=s.replace("exp.textContent=hasChildren?(this.collapsed.has(n.id)?'▸':'▾'):'·';exp.disabled=!hasChildren;","exp.textContent=hasChildren?'▸':'·';exp.classList.toggle('expanded',hasChildren&&!this.collapsed.has(n.id));exp.disabled=!hasChildren;")
 s=s.replace("if(hasChildren){const box=document.createElement('div');box.className='children'+(this.collapsed.has(n.id)?' collapsed':'');children.forEach(ch=>box.appendChild(this.renderNode(ch,depth+1,keep,null)));wrap.appendChild(box)}","if(hasChildren){const box=document.createElement('div');box.className='children'+(this.collapsed.has(n.id)?' collapsed':'');const inner=document.createElement('div');inner.className='children-inner';children.forEach(ch=>inner.appendChild(this.renderNode(ch,depth+1,keep,null)));box.appendChild(inner);wrap.appendChild(box)}")
 a="contextAction(action){const id=this.selectedId,n=this.state.nodes[id];if(!n)return;this.hideDialogsInstant();"
 b="contextAction(action){const id=this.selectedId,n=this.state.nodes[id];if(!n)return;if(action==='move'){this.hideDialogsInstant();return this.startMove(id)}this.contextParentId=id;this.returnModal='#contextSheet';"
 s=s.replace(a,b).replace("if(action==='move')return this.startMove(id);","")
 s=s.replace("C.setStatus(this.state,this.clock,n.id,status);this.hideDialogsInstant();this.changed","C.setStatus(this.state,this.clock,n.id,status);this.restoreContextSheet();this.changed")
 s=s.replace("C.editNode(this.state,this.clock,n.id,{title,description:$('#editDescInput').value});this.hideDialogsInstant();this.changed","C.editNode(this.state,this.clock,n.id,{title,description:$('#editDescInput').value});this.restoreContextSheet();this.changed")
 s=s.replace(" openSettings(){"," restoreContextSheet(){if(this.returnModal==='#contextSheet'&&this.contextParentId&&this.state.nodes[this.contextParentId]&&!this.state.nodes[this.contextParentId].deleted){const id=this.contextParentId;this.returnModal=null;this.contextParentId=null;this.hideDialogsInstant();this.openContext(id)}else this.hideDialogsInstant()},\n setNavCollapsed(collapsed,save=true){this.navCollapsed=!!collapsed;const h=$('#topbar'),b=$('#navCollapseBtn');h.classList.toggle('nav-collapsed',this.navCollapsed);if(b){b.setAttribute('aria-expanded',String(!this.navCollapsed));b.setAttribute('aria-label',this.navCollapsed?'네비게이션 펼치기':'네비게이션 접기')}if(save)try{localStorage.setItem('mira-checklist-nav-collapsed',this.navCollapsed?'1':'0')}catch(_){}} ,\n openSettings(){",1)
 s=s.replace("requestCloseCurrent(){if(this.currentModal==='#commentsDialog')return this.requestCloseComments();if(this.currentModal==='#commentEditDialog')return this.requestCloseCommentEdit();this.closeDialogs(true)}","requestCloseCurrent(){if(this.currentModal==='#commentsDialog')return this.requestCloseComments();if(this.currentModal==='#commentEditDialog')return this.requestCloseCommentEdit();if(this.returnModal==='#contextSheet')return this.restoreContextSheet();this.closeDialogs(true)}")
 a=s.find(" handleHeaderScroll(){");b=s.find(" smoothWheel(e){",a)
 if a>=0 and b>a:s=s[:a]+s[b:]
 return s.replace("await sleep(540);root.classList.add('boot-out');await sleep(750);$('#app').classList.remove('app-hidden');$('#app').classList.add('app-reveal');await sleep(540);root.remove();","await sleep(420);$('#app').classList.remove('app-hidden');root.classList.add('boot-out');await sleep(420);root.remove();")
rw(Path("shared-web/app.js"),js)
css='''
/* v2.1.2 polish */
html,body,.app-shell{width:100%;max-width:100%;height:100%;height:100dvh;overflow:hidden}body{overscroll-behavior:none}.topbar{transform:none!important;margin-top:0!important;transition:none!important}.brand{padding-bottom:10px}.brand-divider{height:1px;margin:0 -2px 9px;background:linear-gradient(90deg,transparent,var(--violet) 12%,rgba(167,139,250,.78) 50%,var(--violet) 88%,transparent);box-shadow:0 0 8px rgba(167,139,250,.24)}.nav-details{display:block!important;max-height:420px;opacity:1;transition:max-height 220ms cubic-bezier(.22,.61,.36,1),opacity 150ms ease!important;overflow:hidden}.topbar.nav-collapsed .nav-details{max-height:0!important;opacity:0}.nav-collapse-btn{display:block;width:100%;height:13px;margin:5px 0 -3px;border:0;background:transparent;position:relative;padding:0}.nav-collapse-btn::before{content:'';position:absolute;left:50%;top:5px;width:46px;height:3px;border-radius:9px;background:#31515a;transform:translateX(-50%)}.nav-collapse-btn span::after{content:'⌃';position:absolute;left:50%;top:-5px;transform:translateX(-50%);font-size:10px;color:var(--muted);transition:transform 180ms ease}.topbar.nav-collapsed .nav-collapse-btn span::after{transform:translateX(-50%) rotate(180deg)}.expand-btn{margin-right:-20px!important;transition:transform 145ms cubic-bezier(.22,.61,.36,1)!important;transform:rotate(0deg)}.expand-btn.expanded{transform:rotate(90deg)}.children{display:grid!important;grid-template-rows:1fr;opacity:1;margin-top:6px;transition:grid-template-rows 210ms cubic-bezier(.22,.61,.36,1),opacity 145ms ease,margin-top 210ms ease;overflow:hidden}.children-inner{min-height:0;overflow:hidden;display:flex;flex-direction:column;gap:6px}.children.collapsed{display:grid!important;grid-template-rows:0fr;opacity:0;margin-top:0}.filter.secondary:focus{outline:none}.boot-intro{width:100vw;height:100dvh;transform:none!important}.boot-intro.boot-out{opacity:0!important;transform:none!important;transition:opacity 360ms ease!important}.app-reveal{animation:none!important}.title-row h1{font-size:clamp(18px,4.8vw,24px)}.overall-card,.toolbar-row>*,.filters,.node-row,.node-main{min-width:0}.node-main{overflow:hidden}.node-title,.node-desc{overflow-wrap:anywhere}@media(hover:none){.toolbar-btn:hover,.filter:hover{border-color:var(--line);color:var(--muted)}.filter.active:hover{background:rgba(97,231,242,.12);border-color:var(--cyan2);color:var(--cyan)}}@media(max-width:720px){.topbar{padding-top:max(10px,env(safe-area-inset-top));padding-left:max(7px,env(safe-area-inset-left));padding-right:max(7px,env(safe-area-inset-right))}.filters{grid-template-columns:repeat(5,minmax(0,1fr));width:100%}.filter,.filter.secondary{font-size:clamp(9px,2.6vw,11px);padding-inline:2px}}@media(max-width:380px){.filters{gap:3px}.filter,.filter.secondary{font-size:9px}.tree-scroll{padding-left:6px;padding-right:6px}}
'''
rw(Path("shared-web/style.css"),lambda s:s+css)
for sub in ["android/app/src/main/assets/web","windows/web"]:
 d=r/sub
 for n in ["app.js","index.html","style.css"]:(d/n).write_text((r/"shared-web"/n).read_text(encoding="utf-8"),encoding="utf-8")
rw(Path("android/app/build.gradle"),lambda s:s.replace("versionCode 20101","versionCode 20102").replace("versionName '2.1.1'","versionName '2.1.2'"))
for x in ["android/app/src/main/java/com/absolute/checklist/MainActivity.java","windows/MainWindow.xaml.cs"]:rw(Path(x),lambda s:s.replace("2.1.1","2.1.2"))
